[package]
name = "bar"
version = "0.0.0"
authors = ["edwin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
foo = {path = "../foo", version="0.0.0"}
